name: asp_plot
channels:
  - conda-forge
dependencies:
  - flake8
  - black
  - pre_commit
  - pytest
  - pip
  - numpy
  - rasterio
  - rioxarray
  - matplotlib
  - fiona
  - pandas
  - gdal
  - geopandas
  - contextily
  - pyproj
  - scipy
  - shapely
  - xarray
  - matplotlib-scalebar
  - click
  - sliderule
  - fpdf2
