name: asp_plot
channels:
  - conda-forge
dependencies:
  - flake8
  - black
  - pre_commit
  - pytest
  - pip
  - numpy
  - rasterio
  - matplotlib
  - fiona
  - pandas
  - gdal
  - geopandas
  - contextily
  - matplotlib-scalebar
  - click
  - geoutils
  - xdem
  - pip:
    - markdown-pdf
